### ISSUE TITLE
Multires models examples ?

### ISSUE THREAD

**Issue by wiztigers** [cnr-isti-vclab/3DHOP#11]
Hello,

I'm currently working with the University of Strasbourg (unistra) on a Django based 3D file sharing web solution, and I'm testing 3DHop integration.
I'd like to thank you for this initiative : it seems great, and we'd love to use it !

However, although everything is fine when displaying single res `.ply` files, I've got issues when trying to display multires `.nxs`/`.nxz` files.
For example, let's consider `3DHOP_4.2/examples/HOWTO_2.0_models_loading.html` (without any modification), with **Firefox 63.0** :
* Whether I directly open the file, or if I start a small webserver with `python -m SimpleHTTPServer`, canvas remains empty : only background image is displayed, neither the `.nxz` gargoyle nor the `.ply` cage appear.
* If, inside `3DHOP_4.2/examples/HOWTO_2.0_models_loading.html`, I change the path `models/multires/gargo.nxz` to `models/singleres/gargo.ply` the gargoyle and the cage display properly (gargoyle's head is stuck in the cage floor, but that's not a problem).
* If I visit http://vcg.isti.cnr.it/nexus/demo.html?model=models/monreale.nxz , the model is properly displayed, with the different LOD appearing sequentially over a couple seconds.
* When 3DHOP viewer is used inside my Django server, behaviour is the same: `.ply` display fine, `.nxs`/`.nxz` don't appear at all.

When comparing to **Chromium 70.0.3538.77** (same file: `HOWTO_2.0_models_loading.html`) :
* `gargo.nxz` doesn't display when simply opening the file
* When viewing the file through a simple webserver (`python -m SimpleHTTPServer`), `gargo.nxz` is properly displayed.
* Running chromium-browser with `--allow-file-access-from-files` CLI option doesn't seem to change the results.

For information, if I test it via my Django app, with scenes consisting only of one mesh and one model :
* `.ply` files, even complex scenes, are displayed properly, whether I use Firefox or chromium.
* With **Firefox**, `gargo.nxz` doesn't display and I get the following error:
```
TypeError: modelDescriptor is null[Learn More] presenter.js:1548:2
_onPlyLoaded                            http://localhost:8000/site_media/js/3pp/3dhop/presenter.js:1548:2
setScene/<.onSuccess</<                 http://localhost:8000/site_media/js/3pp/3dhop/presenter.js:2910:55
_dispatch                               http://localhost:8000/site_media/js/3pp/3dhop/spidergl.js:29:10470
_doOnSuccess                            http://localhost:8000/site_media/js/3pp/3dhop/spidergl.js:29:11269
SpiderGL.IO.XHRRequestBase/i.onload     http://localhost:8000/site_media/js/3pp/3dhop/spidergl.js:29:13911
```
* With **Chromium**, `gargo.nxz` doesn't display either and, after a few moments of awkward browser freeze, I get the following error :
```
Uncaught TypeError: Cannot read property 'extra' of null
  at Presenter._onPlyLoaded (presenter.js:1548)
  at sglRequestBinary.onSuccess (presenter.js:2910)
  at SpiderGL.IO.BinaryRequest._dispatch (spidergl.js:29)
  at SpiderGL.IO.BinaryRequest._doOnSuccess (spidergl.js:29)
  at XMLHttpRequest.i.onload (spidergl.js:29)
```
(I don't ask you to debug my Django app, of course ^^  Just to make a single multires example work would be a huge step towards using 3DHOP)

I've checked every `.nxz` files I use with nexus' `nxsview` tool, they don't seem to have any problem (_ie._ they display properly).
I've tested with 3DHOP_4.2 downloaded version as long as with this repo's master latest version (d428e9), results are the same.

Should the example demos work out of the box on all browsers ?
Should I setup / modify something before running them ?

If it's of any help, besides the browser versions I cited, I'm on a Dell Latitude 5490 running LinuxMint 19 (64-bit).

Thanks in advance for your directions ! Have a nice day ! :+1:

**Comment by potenziani** [comment]
Hi @wiztigers, let's try to clarify your doubts...

First of all: yes, 3DHOP has been designed to work on all the main browsers and on all the main OS (this includes also Linux, even if clearly is not possible for us testing all the Linux distro).

Moving to your issues, a good strategy to solve them consists in going step by step: firstly, to check if 3DHOP works in your system try to run whatever examples you can find in the 3DHOP official website (http://3dhop.net).

Once you are sure your system can run the 3DHOP examples online you can start using it. 
As you can read here (http://3dhop.net/documentation/3DHOP_Environment_Deployment.pdf), 3DHOP needs a web server to works: you can upload the distribution package on a proper server (if you have it at hand), or you can install a local web server on your pc (we usually use Apache HTTP Server). 
Without a web server installed the browser is unable to handle external files due to the CORS (Cross Origin Resource Sharing) policy (some browsers can, but in general this is not true). Because of this, if you try to open an HTML file that includes the 3DHOP viewer in a browser without the web server support, you just will get an empty CANVAS (no chances to visualize a Nexus file).
The "--allow-file-access-from-files" workaround works very well in Windows Chrome, but it is browser and OS dependent (also, remember to close all the Chrome instances and then start again the browser to be sure this workaround works), so we strongly advice to rely on a web server.

Now, if you are able to run all the 3DHOP examples on your web server, you are ready for embedding 3DHOP in your Django application (but this should be just the last step).

Hope this can help you. If you instead still need help, please contact us using the technical support account: info@3dhop.net.

Thanks for using 3DHOP, and have a nice day you, too!

**Comment by wiztigers** [comment]
Hi @potenziani , and thanks a lot for your quick answer.
My system is indeed able to run 3DHOP examples : after your directions, I installed Apache and, once I copied 3DHOP examples in it, everything worked flawlessly.
So, according to your directions, it seems the problem may lie in the  handling of external files : python's `SimpleHTTPServer` does not support that, but Apache default install does seem to.

Anyway, the problem lies in my configuration of Django, not in 3DHOP. That's good news !
I now have to fiddle around with Django's default config to sort out where the problem lies. ᕦ(ò_óˇ)ᕤ

Thanks once more !
Do you want us to keep in touch as my project progresses further ?
