### ISSUE TITLE
feature request: transitions & texture switching

### ISSUE THREAD

**Issue by TJRL** [cnr-isti-vclab/3DHOP#15]
Hi, thanks for developing this great app. Especially the multi resolution feature is awesome. Playing around with it I noted two things that I'd like to see and that are missing.

1. When turning on and off models, it would be nice to have them gradually fade in/ out or morph rather than simply a hard switch. More generally, some animation/transition capacity would be really useful.
2. I would like to have the option to be able to switch between textures. In my case I have models with a number of baked textures respresenting different surface visualization modes that help to visually analyse scanned artefacts and landscapes.

So I was curious what you think about these features and whether there was anything like this planned for future releases.

Thanks.

**Comment by potenziani** [comment]
Hi @TJRL ,
thanks for your appreciation and feedback.

Concerning your considerations:
1. this is an interesting point, so far we never considered something like this. For sure it is a nice feature, mostly from the "aesthetics" point of view. Nevertheless, it could require a not negligible code changes, and currently more structural features are characterized by a higher priority;
2. actually this features is already in our to-do list. It requires a good developing effort, primarily in re-design the Nexus pre-processing action, and secondly in modifying the rendering/streaming stage... However, since we have a lot of people interested in it, we are hoping to see it integrated into 3DHOP in the not too distant future. 

Hope I have fulfilled your requests, thanks again & best

**Comment by TJRL** [comment]
Hi @potenziani, 
thanks for your answer! 
Regarding my first point: I studied the API better and figured it's not too hard to animate the transparency value of models in order to create smooth transitions. So that's great!
As for the second, good to hear it's in the pipeline! For now I simply switch between more copies of the same model but with each a different texture.

I really love the versatility of 3DHOP as it already is. Looking forward to further developments!
