### ISSUE TITLE
shaders and mesh analysis

### ISSUE THREAD

**Issue by TJRL** [cnr-isti-vclab/3DHOP#18]
Hi, another shameless feature request from me. Radiance Scaling and curvature visualization are amongst the most useful visual inspection tools for meshes of artefacts. I saw that MeshLabJS has the capacity to do this in the browser... So any plans to bring this functionality to 3DHOP? It would be a really awesome and very useful extension to 3DHOP.
Best,
Tijm

**Comment by potenziani** [comment]
Hi @TJRL ,

of course, radiance scaling and screen-space curvature are useful visualization schemes. 

Since these are mostly shaders-dependant inspection tools, their implementation in 3DHOP is certainly possible. However, they also require a rendering approach based on multiple passes (currently completely missing on 3DHOP). 
Moreover, these visualization schemes are very specialized, and so, difficult to integrate with other rendering modes (let's think for instance to transparency). 
Finally, as you told, radiance scaling and curvature visualization are mostly inspection tools, and so they fit just partially with the scope of a publishing/presentation tool like 3DHOP.

For all these reasons, currently implementing these features is not in our plans, and most probably they will not be in our to-do-list in the near future.

However, hereafter, ad-hoc 3DHOP's versions with radiance scaling and curvature visualization could be developed (by us or by our community of users) for specific projects... so, never say never!

**Comment by TJRL** [comment]
Thanks for the answer, @potenziani . The reason I'd like to have these tools in 3DHOP is that it can be useful in the presentation of interpretations of artefacts based on these shaders.
I have sort of a solution, namely by baking these shaders as textures. For potential future readers of this topic, interested in this: It's not possible to do this in meshlab (as far as I know), but Blender's pointiness node can give you very similar effects, and can be baked. So, the disadvantage of this method is that it is not interactive, and that 3DHOP can't display multiple textures (yet), so switching between them is not yet possible.
