### ISSUE TITLE
3DHOP freezes

### ISSUE THREAD

**Issue by TJRL** [cnr-isti-vclab/3DHOP#19]
Hi, I have built an application to compare the results of 3D scans. It works fine, and than after switching between models a number of times and navigating the 3D space, it freezes. It doesnt occur after a specific period of time, sometimes it takes a few minutes, sometimes it occurs already after 20 seconds. It occurs in all browsers the same way. This is the link to the application:
http://www.4dresearchlab.nl/3DHOP/lijfje/lijfje.html
I noticed it stores all the models in the memory as soon they're loaded, so with so many high res models, at some point RAM usage is quit high, but it never reaches my pc's max RAM. So I guess this isnt the problem.

**Comment by potenziani** [comment]
Hi @TJRL ,
first of all congrats for your app, it seems to be very nice!

I'm playing with it from a while, without getting any freezing, so probably you are right, the problem could be somehow related to the amount of data you are visualizing and to your specific HW/SW configuration. 
Could you provide some more info about your HW/SW system? Also, could you provide some more info about the models you are visualizing? 
From what I can see, you are simultaneously managing 10 NXZ models, 3 of them with textures (2*4096 for each of them), am I right?

Moreover, I noticed that you have some errors in the console (also involving the nexus "updateCache" function). Did you already isolate what is causing these errors?

**Comment by TJRL** [comment]
Hi @potenziani,
thanks!
it took me a few minutes, and I almost believed it didnt freeze today but it did in the end. I have seen the freeze occur on various systems. 
Are you talking about the HW/SW configuration of the system I'm working on or of the server that hosts the files and app?
I'm managing 8 different nxz files, between 2 and 15 million faces (the 5th and 10th radio button lets you empty the model slot for the back and front side of the textile model, that's why it seems 10 ;) ). Produced in photogrammetry software metashape and with some other 3D scan software in case of the structured light scans. The models were further processed in meshlab. Those with textures have 2*4096 yes.
The freezing by the way also occurs in the other app I [made](http://www.4dresearchlab.nl/3DHOP/MT/muro_tenente.html). But this one has just one high res model.

Regarding the errors. I didnt get errors related to the updateCache. I do get this error though: `Error: WebGL warning: checkFramebufferStatus: Framebuffer not complete. (status: 0x8cd7) ` This one starts with the initial loading of the model, and repeats with actions such as measuring and point picking. Otherwise I get errors about unreferenced CSS declarations, which isnt really a problem.

By the way, I do get all the same errors with the [demo files](http://www.4dresearchlab.nl/3DHOP/minimal/index_all_tools.html) that are supplied with 3DHOP.

**Comment by TJRL** [comment]
@potenziani I've updated the post above after some more testing.

**Comment by potenziani** [comment]
Hi @TJRL ,
finally I got the browser freeze, too (and in a quite performing system, so we can guess it not depend by the HW/SW configuration).

The problem is not related to the `net::ERR_CACHE_OPERATION_NOT_SUPPORTED` error (due to a known [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=770694) characterizing Chromium-based browsers), neither to the message `Error: WebGL warning: checkFramebufferStatus: Framebuffer not complete. (status: 0x8cd7)` (that's not an error but just a warning).

Instead, it seems due to an issue related to the textures, since the console's errors I get basically in all the main browsers, point out problems with textures requests...

Chrome:
![chrome](https://user-images.githubusercontent.com/2982503/60031000-3d5fc400-96a4-11e9-9ad8-011190faa182.png) 

Firefox:
![firefox](https://user-images.githubusercontent.com/2982503/60031108-697b4500-96a4-11e9-8f98-f4e51f715397.png)

Edge:
![edge](https://user-images.githubusercontent.com/2982503/60031120-6d0ecc00-96a4-11e9-8540-46bd205e92a5.png)

Debug your app starting from these few messages is not so easy... 
I would need to know something more about your application... For instance, did you modify some of the 3DHOP "core" files (presenter.js, nexus.js, etc.)?
Also, did you try to update your 3DHOP version to the latest DEVELOPMENT version?

**Comment by TJRL** [comment]
Hi @potenziani ,

that is strange, I don't get this Chrome error you show me. This is all I get, many times over:
![afbeelding](https://user-images.githubusercontent.com/22885764/60331331-b442d880-9994-11e9-9b47-535c3bb92d8b.png)
So it also tells me that it is 'recovering geometry' and 'recovering texture', referring to different nodes. I'm not sure whether this is pointing to something problematic or just reporting something regular in the console. Or has this something to do with the bypassing of that chrome bug?

I do get the TypeError message in firefox. It starts to occur and repeat when I turn on the texture of one of the models, but than never stops showing even when the texture is not displayed, and even when the model with the texture is not displayed. Also, the error occurs specifically with only two of the three of the models with textures (the lower two in the model list).

In any case, although the textures are the cause of the errors, the freezing occurs regardless of these errors, on random moments.

As regards to your questions:
I didn't modify the 3DHOP core files, and I didn't update to development version. Do you suggest I should try that?

**Comment by potenziani** [comment]
Hi @TJRL ,
yes, as I told you the network error messages you reported are related to the Chrome bug, and are not a problem for 3DHOP (when this error occurs 3DHOP activates a recovery procedure and you get the "Recovering geometry/texture for node ..." log message). 
So, don't worry... and if you want to clear your console from this kind of errors just select the "Hide network" checkbox in the "Console settings" panel: 

![Annotazione 2019-06-28 170822](https://user-images.githubusercontent.com/2982503/60352062-5bd8fe80-99c7-11e9-9d2d-6458ded7a3ac.png)

Instead, the "TypeError" message is strange and needs to be further investigated (and on my Chrome and Edge it happens exactly as in firefox for you). However, try to update 3DHOP to the DEVELOPMENT version, check it, and let us know if your system will get freeze again.
