### ISSUE TITLE
Modifying Touch Sensitivity

### ISSUE THREAD

**Issue by ElectricEye89** [cnr-isti-vclab/3DHOP#23]
I am working on using the 3Dhop viewer on a kiosk, and I am having trouble locating where I can increase the sensitivity of touch rotation. The viewer works fine on most mobile devices, however, on the kiosk, you have to drag a long ways across the screen, and get little progress in rotation. 
Any help would be much appreciated!

**Comment by TJRL** [comment]
Hi @ElectricEye89 , 

I don't think there is an easy way to adjust mouse sensitivity. The orbit speed is relative to screen coordinates of the mouse pointer or touch location, so with big touch screens it will go slower. You'll have to find where this is defined in the core files, and adjust the function that transfers the screen coordinates to trackball position. Another option would be to make a mini trackball, similar to the mini light trackball as seen in [this application](http://vcg.isti.cnr.it/alchemy/viewer/index.html#loaded). Again, you'll need to adjust the code that is used to make this mini trackball, in order to make it control the view direction trackball rather than light direction.

But I'm just a user and perhaps the developers have a better solution I'm not aware of.

**Comment by potenziani** [comment]
Hi @ElectricEye89 ,

if you want to modify the mapping of dragging interactions (rotation and pan) in 3DHOP, you just need to edit the numeric values at the end of lines 2683/4 in 3DHOP 4.2 (or lines 2604/5 in current 3DHOP DEVELOPMENT version) in the "presenter.js" file:

`if(ui.dragDeltaX(button) != 0) this.x += (ui.cursorDeltaX/500);`
`if(ui.dragDeltaY(button) != 0) this.y += (ui.cursorDeltaY/500);`

If you substitute 500 with lower values, you will get a "more responsive" interaction...

Warning: this change will act on every kind of interaction (mouse + touch) and (of course) on all the devices. So, it is ok if you are working on a closed kiosk, but probably it is not the better option if your app is online.
In the latter case, please check the issue mentioned by @TJRL (by the way, thanks for your answer!), it will require you some more effort, but, at the same time, it will allow you to edit just the touch mapping.

**Comment by ElectricEye89** [comment]
Thank you both for the quick response. Since we only needed this to reflect in our Kiosk, we were able to adjust that 500 value down in the presenter.js file, and it works like a charm!

Thanks again!
