### ISSUE TITLE
Resizing after full screen view in Firefox not working properly

### ISSUE THREAD

**Issue by bellerophons-pegasus** [cnr-isti-vclab/3DHOP#25]
We are using 3DHOP in an application to display ancient vases: https://odeeg.acdh.oeaw.ac.at/vases/object/detail/1

I had to remove "width:100%" and "height:100%" from 3dhop.css #draw-canvas (line 44) in order to properly display the small viewer along the other content.

The only remaining problem now is that when in Firefox I switch to Full Screen and then go back via "Exit Full Screen" or Esc the canvas dimensions are still set to full screen dimensions which results in the 3d model extending over all the other content on display. On Chrome this problem does not exist.

Any help would be appreciated very much.

**Comment by bellerophons-pegasus** [comment]
Oh yes, the version I am using is 4.2 - Release: 6 Jun 2018

**Comment by potenziani** [comment]
Hi @bellerophons-pegasus ,
the issue is not due to the 3dhop.css setup (so you can revert line 44 to the original values) but to the init.js file.

Here it is a new version of init.js that should comply with the flex design of your website: [init.zip](https://github.com/cnr-isti-vclab/3DHOP/files/3486700/init.zip) (probably it will be the default version in the next 3DHOP release, but we need to do some additional test on it).

Try it and let us know if everything works!

PS: before to try the new init.js file, please clean the redundant (and potentially dangerous) style definitions in your main HTML file:

**_line 301_** 
from
`<div id="3dhop" class="tdhop" onmousedown="if (event.preventDefault) event.preventDefault()" style="width: 1920px; height: 888px;">`
to
`<div id="3dhop" class="tdhop" onmousedown="if (event.preventDefault) event.preventDefault()" style="min-height:350px;">`

**_line 312_**
from
`<canvas id="draw-canvas" style="min-height: 350px;" width="1920" height="888" tabindex="0">`
to
`<canvas id="draw-canvas" tabindex="0">`

**_line 314_**
`moveToolbar(0,5);`
simply to be deleted (since you are already defining it at _line 302_ `<div id="toolbar" style="left: 0px; top: 5px;">`)

**Comment by bellerophons-pegasus** [comment]
Hi @potenziani ,
thank you for your quick response. I just tried it out on my local machine and the new init.js file works like a charm!

By the way: the width and height from line 301 and 312 are added automatically by some js; I am not sure if it is the one from 3DHOP, or something done by bootstrap.

The minimal height on line 314 is needed, because otherwise the button menu is too large and flows over to the next viewer below.

**Comment by bellerophons-pegasus** [comment]
Also the style settings for #toolbar on line 314 come from the js, because of 'moveToolbar(0,5)'
Otherwise it would be places a little bit more inside the containing div  ;-)

**Comment by potenziani** [comment]
Hi @bellerophons-pegasus ,
perfect, glad to see that everything works fine now! :-)

My fault, for sure the inline style definitions have been added by the "brute force" webpage download (I couldn't be sure, but I should have imagined it). Instead, concerning the minimal height, it is better to move it to the 3dhop general div container instead of having it just on the canvas. ;-)
