### ISSUE TITLE
keyboard input disabled

### ISSUE THREAD

**Issue by IroMp** [cnr-isti-vclab/3DHOP#26]
Hello, I have created an input field `type=text` in the page where 3DHOP viewer is embedded and it is deactivated when WebGL content is fully loaded. It seems that it prevents from writing any text in that field. Have you ever encounter this issue?

**Comment by potenziani** [comment]
Hi @IroMp,
the issue was due to the bad management of the webpage focus in 3DHOP. Please download the latest DEVELOPMENT version of 3DHOP (in the GitHub DEVELOPMENT branch) to solve it.

PS: please notice that if (and only if) you want to add an input text field as overlay panel inside the main 3DHOP DIV element (the one with `id="3dhop" class="tdhop"`), you also need to remove (at your risk) the `onmousedown="if (event.preventDefault) event.preventDefault()"` command from its definition.

**Comment by IroMp** [comment]
I'll download it, thank you!
