### ISSUE TITLE
Objects have limited rotation angle in certain axes (usually Y and Z)

### ISSUE THREAD

**Issue by Antsushi** [cnr-isti-vclab/3DHOP#32]
Hi,

First of all, thank you for creating this software, it's fantastic! Unfortunately I am having an issue with the rotation of my models. The rotation issue can be observed in many of the galleries in your website on the "gallery" page, for example:

http://cyclamen.cyi.ac.cy/sites/3DV/3dhop.html

http://cabinetdecuriosites3d.mnhn.fr/fr/content/cro-magnon-1-homo-sapiens

http://vcg.isti.cnr.it/3dhop/demos/musa/index_musa.html

While I cannot show you my own models in 3Dhop as the website is currently under construction, I can provide screenshots from both 3Dhop and MeshLab, which I think might help elucidate the issue.

![3dhop rotation issue](https://user-images.githubusercontent.com/57841891/73356315-fa954880-4291-11ea-89ea-0d39a4c284e7.png)

On the left is my model rotated along the Z axis in 3Dhop up to the point where it cannot be further rotated. On the right is the same model with its bounding box in MeshLab. Both are in the same orientation. It seems that the "plane" of rotation in 3Dhop caps the bounding box at exactly 90 degree of rotation along the Z axis, not allowing it to rotate further. Am I understanding it right? Is there a way to circumvent it? 

It's just that I am planning to have hundreds if not thousands of .ply files of various anatomical items (bones, teeth) on my website, and the inability to fully rotate an object will limit the usability of the models, as some anatomical views and planes will not be available to the user. I know I can rotate the objects in MeshLab prior to loading them to 3Dhop, but it would just introduce a lot of additional work. 

However it does seem that there's a way to circumvent the issue, seeing that this gallery for example has models that can be rotated freely and fully along all axes.

http://bonify.archaeolabs.nl/app/species/goat/mandibula_1.php

Thank you!

Best,
Mike

**Comment by potenziani** [comment]
Hi @Antsushi ,

as you can read [here](http://3dhop.net/examples.php?id=3) 3DHOP provides 4 different trackballs to design interactions tailored on the object(s) you want to publish/visualize: 
- **turntable** (default), this trackball always preserves the vertical axis, so it is extremely useful when you want to rotate around an object fixed in a center of rotation;
- **pantilt**, this trackball is especially suited to manage mostly-flat, vertically-mounted objects like bas-reliefs or wall panels, with an interesting front side, but nothing to see on the other sides;
- **turntable_pan**, this trackball is an extension of the turntable trackball, that also allows the user to pan across the object, changing the center of rotation;
- **sphere**, this trackball is implemented as a generic virtual trackball with six degrees of freedom, so basically it enables full and free rotation and panning on all axes, making it possible to reach every possible view direction.

So, the limitations you are facing actually are just due to specific setups of these trackballs.
If you want to design a viewer with non-limited (but more difficult to use for novice users) interactions, the spherical trackball is what you need!
 
I hope I was helpful, otherwise let us know.

Ps: check #24 for a more technical discussion on trackballs.

**Comment by Antsushi** [comment]
@potenziani Oh, that's fantastic! I should have read the How To page much more carefully... 

Thank you!
