### ISSUE TITLE
Implementing 3DHOP in Rails

### ISSUE THREAD

**Issue by mashalahmad** [cnr-isti-vclab/3DHOP#33]
Hi

I got the uncaught reference error at presenter file on the following line
SpiderGL.openNamespace(); 
error 
Uncaught ReferenceError: SpiderGL is not defined

can you tell whats the reason??

**Comment by potenziani** [comment]
Hi @mashalahmad 

it is not possible to debug your issue without further information (3DHOP version, HW and SW system setup, etc).

Anyway, it seems to be a problem related to the non-inclusion of the spidergl.js file. Please, make sure you've included it in your HTML file (`<script type="text/javascript" src="js/spidergl.js"></script>`) and in the js folder of your project.

**Comment by mashalahmad** [comment]
thanks I resolved that issue. Im trying to implement 3DHOP in rails. I am able to see the background image but model is not loading here is the piece of code 
var presenter = null;

```
function setup3dhop() { 
	presenter = new Presenter("draw-canvas");

	presenter.setScene({
		meshes: {
			"Gargoyle" : { url: "assets/images/cube.ply" }
		},
		modelInstances : {
			"Model1" : { mesh : "Gargoyle" }
		}
	});
}

$(document).ready(function(){
	init3dhop();
	setup3dhop();
});
```

I got the error "404 model not found". 
Now in rails usually images are put under the assets/images folder I put the background images there and they are loading but not the model

**Comment by mashalahmad** [comment]
here is the screenshot 
![error](https://user-images.githubusercontent.com/31829812/76616013-0758bd80-651b-11ea-9083-c1ddc9b73ed2.png)

**Comment by potenziani** [comment]
Hi @mashalahmad 
I do not have experience with Rails, so my help can only be partial.

In a common setup (local/remote HTTP web server) changing the relative folder of the resources (skins, css, js, models) is not a problem for 3DHOP. Of course, this means you have to update all the paths pointing those resources (and this could be the error causing the SpiderGL issue you reported previously).

Anyway, what you are reporting is really strange, since usually the HTTP error 404 simply means that the resource you are trying to load not be found on the server... But, if starting from the folder with the HTML file containing the 3D scene setup, the relative path of the model is right (**assets/images/cube.ply**), and the model **cube.ply** really is in the **assets/images** folder, it should work...

**Comment by mashalahmad** [comment]
yeah im also very amazed. the same thing was previously happening to my background image so I included the ruby tag and background image was then displayed. Im not sure if I can do the same with java script in ruby or not. thanks btw
