### ISSUE TITLE
Setting tabindex on canvas messes with focus in Firefox

### ISSUE THREAD

**Issue by felmab** [cnr-isti-vclab/3DHOP#35]
SpiderGL adds the `tabindex="0"` attribute on the `<canvas>` element. To begin with, in order to help us better understand this issue, what is the purpose of this?

In Firefox (tested with version 74 under Archlinux and Ubuntu), but not in Chrome (more precisely Chromium), it seems this behaviour messes with focus, namely text selection disappears when the mouse button is released, and a select list does not remain open. This could be observed on [our website](https://cabinetdecuriosites3d.mnhn.fr/en/content/syninclusion-dinsectes-dans-lambre) up until now, but since I am going to implement a workaround (by removing the attribute later in JavaScript), here is [another example](https://odeeg.acdh.oeaw.ac.at/vases/object/detail/1). Manually removing the attribute when inspecting the code disables this behaviour. Although I tried to understand this interaction, I could find nothing on this topic which could explain this.

**Comment by potenziani** [comment]
Hi @felmab 
the issue you are experiencing is not related to "tabindex", but to a wrong focus command included in the interface source code (init.js). This bug has already been fixed in the DEVELOPMENT version of 3DHOP, as you can see below (tabindex + text selected _in_ FIREFOX + 3DHOP DEV):

![Annotazione 2020-04-15 150615](https://user-images.githubusercontent.com/2982503/79340644-e4129b00-7f2a-11ea-89a6-2a83510d8cdf.png)

Since both the projects you linked are using 3DHOP 4.2, my suggestion is to update your 3DHOP distribution, and then to check again (actually it is our fault, it's been a while since we last merged the DEV branch into the MASTER ... we hope to do it shortly).

Anyway, to answer to your question, SpiderGL uses "tabindex" to "focus" the webpage on the canvas when it is not completely visible. 

Let me explain: let pretend you are in this situation A (left image). When you click on the canvas the page automatically scrolls up to the top of the canvas, as in B (right image).

![c](https://user-images.githubusercontent.com/2982503/79330409-c38e1500-7f19-11ea-9d50-c5c1275c1fa6.png)

This sort of trick was thought (years ago) to help final users interactions, without touch (and mess) the browsers "official" focus routine. Unfortunately nowadays SpiderGL begins to age, and some of its features are a little dated. For instance, currently the tabindex trick works just in Chromium-based browsers. Moreover, these kinds of page controls aren't considered anymore a good thing in modern web design...

For all these reasons (but not only), in the next months 3DHOP will go through a renewal process, which will most likely include a serious reconsideration of the SpiderGL library.

However, this not means that temporary fixes will not be released in the meanwhile (like probably will happen with the "tabindex" feature). 
So, stay tuned, and remember to keep your code updated with the latest 3DHOP DEVELOPMENT version!

**Comment by felmab** [comment]
Thanks @potenziani, I'll try to update to the latest dev version as advised.
