### ISSUE TITLE
Textured objects are not displayed on iOS

### ISSUE THREAD

**Issue by FunnyPaul** [cnr-isti-vclab/3DHOP#43]
**Configuration (please complete the following information):**
 - Device: iPhone
 - OS: iOS 14.x
 - Browser Safari (iOS), Chrome(iOS)
 - 3DHOP Version 4.3 stable

**Describe the bug**
When I convert a PLY file with texture via `nxsbuild`, it is not displayed on iOS. PC etc. works wonderfully.

If the PLY file is generated without texture (parameter `-u`), however, it works with the display under iOS.

**Comment by potenziani** [comment]
Dear @FunnyPaul ,

sorry for the huge delay in the reply! You probably already solved the problem by yourself, however, since this answer might be useful to other users, here is a tip for successfully using 3DHOP also on iOS devices!

The issue you reported most probably is related to an iOS WebGL2RenderingContext inconsistency bug, already fixed with commit https://github.com/cnr-isti-vclab/3DHOP/commit/0d16e9438a0112be047f86ca629ece20dc83aaf9, in the DEVELOPMENT branch. We did some tests with textured models on Apple devices + iOS 14.x and everything seems to work fine. In the next weeks the DEVELOPMENT branch will be merged into the MASTER branch. Until then, please refer to the DEVELOPMENT branch to overcome this bug, and get the most updated 3DHOP package!
