### ISSUE TITLE
Indication of the level of detail

### ISSUE THREAD

**Issue by hcjghr** [cnr-isti-vclab/3DHOP#9]
Hi,

First of all I want to thank you for an amazing library. I'm looking at using it to display large complex models which will take advantage of the hierarchical display. Given that it can sometimes take longer time or require to zoom in to display the high res details, I was wondering if there is a way to get the information about the current display quality and how it to the user. Given that I haven't seen in any of the examples this feature I'm positive it does not exist yet, but I was wondering if there is a way to just get the info from the presenter and then write my own code to display it.

I hope I managed to explain what I'm interested in :) And again thank you for the amazing work!!

**Comment by mcallieri** [comment]
hi there.

Those information are not available. There is no "current detail level" because the data of the model is loaded AND discarded from the local cache, and different parts of the model are loaded and drawn at different level of detail. 
If you go in debug mode (change the vaue in presenter.js, or call presenter.toggleDebugMode() ), and press 1 on the keyboard, you have a visual feedback of the nexus multiresolution blocks. But it is not possible to have statistics.
The data structure keeps track of the current level of detail for each block, but t is a mess to extract somethign meaninful.
